version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: dev-server
    volumes:
      - ./dev.nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"