version: "3.9"
services:
  nginx:
    image: nginx:1.23.1
    container_name: prod-test-server
    volumes:
      - ./prod-test.nginx.conf:/etc/nginx/conf.d/default.conf

    # to connect to host address it is necessary 
    #   to create docker-compose file with extra_hosts option
    #         and nginx.conf file using it - i.e. host.docker.internal:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"


#  use following command
#   : docker compose -f (X)   docker-compose -f (O)
#  -> docker-compose -f dev.docker-compose.yml -p noveltime-dev-server up